###GET find all projects
GET http://localhost:8080/api/projects

### Find project By ID
GET http://localhost:8080/api/projects/2


### Create new project
POST http://localhost:8080/api/projects
Content-Type: application/json

{
  "id": 6,
  "name": "project 6",
  "description": "created http",
  "createdOn": "2024-07-24",
  "version": null
}

### Update an existing project
PUT http://localhost:8080/api/projects/6
Content-Type: application/json

{
  "id": 6,
  "name": "project 6",
  "description": "updated http",
  "createdOn": "2024-07-24",
  "version": null
}

### Update the project with invalid name
PUT http://localhost:8080/api/projects/6
Content-Type: application/json

{
  "id": 6,
  "name": "",
  "description": "updated",
  "createdOn": "2024-07-24",
  "version": null
}

### Delete a project
DELETE http://localhost:8080/api/projects/6

### Filter projects within a date range
GET http://localhost:8080/api/projects/filter/2024-03-24/2024-07-25